# --- 锚点定义 (通用属性) ---
proxy_providers_common:
  &p {
    type: http,
    interval: 86400,
    proxy: DIRECT,
    health-check:
      {
        enable: true,
        url: https://g.cn/generate_204,
        interval: 600,
        lazy: false,
      },
  }

# 全局过滤节点
exclude:
  &exclude {
    exclude-filter: '群|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|超时|收藏|福利|邀请|好友|失联|选择|剩余|公益|发布|DIZTNA|通路|登录|禁止|定时|渠道|牢记|永久|余额|阁下|本站|刷新|导航|⚠️|@|Expire|http|com',
  }

# --- 基础全局配置 ---

allow-lan: true
ipv6: true
bind-address: '*'
unified-delay: true
tcp-concurrent: true
keep-alive-idle: 600
keep-alive-interval: 60
find-process-mode: strict
external-controller: '[::]:9090'
external-ui: ui
external-ui-url: 'https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip'

profile:
  store-selected: true
  store-fake-ip: true

# --- 代理节点 ---
+proxies:
  - { name: '🇨🇳 直连（IPv4优先）', type: direct, ip-version: ipv4-prefer }
  - { name: '🇨🇳 直连（IPv6优先）', type: direct, ip-version: ipv6-prefer }
  - { name: '🇨🇳 直连（双栈）', type: direct }

chinaDNS:
  &chinaDNS ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']

dns:
  enable: true
  ipv6: false
  listen: :1053
  cache-algorithm: arc
  use-hosts: true
  use-system-hosts: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range-v6: 'fc00::/18'
  fake-ip-filter:
    - '+.cn'
    - 'rule-set:private'
    - 'rule-set:category_ntp'
    - 'rule-set:fakeip_filter'
    - 'rule-set:connectivity_check'
    - 'rule-set:cn'
    - 'rule-set:googlefcm'
    - 'rule-set:steam_cn'
    - 'rule-set:epicgames'
    - 'rule-set:nvidia_cn'
    - 'rule-set:microsoft_cn'
    - 'rule-set:cloudflare_cn'
  default-nameserver:
    - '223.5.5.5'
    - '119.29.29.29'
  nameserver:
    - '1.1.1.1'
    - '8.8.8.8'
  proxy-server-nameserver:
    - 'https://doh.pub/dns-query#DIRECT'
  nameserver-policy:
    '*': 'system'
    '+.arpa': 'system'
    'connectivitycheck.platform.hicloud.com': *chinaDNS
    '+.cn': *chinaDNS
    'rule-set:private,cn,steam_cn,epicgames,nvidia_cn,cloudflare_cn,microsoft_cn,microsoft,googlefcm,apple,spotify': *chinaDNS

hosts:
  'services.googleapis.cn': ['services.googleapis.com']

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP: { ports: [80, 8080-8880], override-destination: true }
    TLS: { ports: [443, 8443] }
    QUIC: { ports: [443, 8443] }
  skip-domain:
    ['Mijia Cloud', '+.oray.com', '+.push.apple.com', 'cloudflare-ech.com']
  skip-dst-address: ['rule-set:telegram_ip']

ntp:
  enable: true
  write-to-system: false
  server: cn.ntp.org.cn

tun:
  enable: true
  stack: system
  auto-route: true
  strict-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack: ['udp://any:53', 'tcp://any:53']

# --- 规则集 ---

# Rule Provider 通用配置
rule_providers_common:
  rp_domain: &rp_domain { type: http, interval: 86400, behavior: domain }
  rp_ip: &rp_ip { type: http, interval: 86400, behavior: ipcidr }
  rp_classical:
    &rp_classical { type: http, interval: 86400, behavior: classical }

rule-providers:
  embylist_domain:
    <<: *rp_domain
    format: text
    url: 'https://raw.githubusercontent.com/wushijujibu/Rules/refs/heads/main/emby_loon.list'
  adblockmihomolite:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/217heidai/adblockfilters@main/rules/adblockmihomolite.mrs'
  DownloadApps:
    <<: *rp_classical
    format: text
    url: 'https://fastly.jsdelivr.net/gh/AIsouler/MyClash@main/Rules/DownloadApps.txt'
  fakeip_filter:
    <<: *rp_domain
    format: text
    url: 'https://fastly.jsdelivr.net/gh/juewuy/ShellCrash@dev/public/fake_ip_filter.list'
  epicgames:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/epicgames.mrs'
  nvidia_cn:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/nvidia@cn.mrs'
  ai:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ai-!cn.mrs'
  youtube:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/youtube.mrs'
  googlefcm:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/googlefcm.mrs'
  google:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.mrs'
  google_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/google.mrs'
  github:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/github.mrs'
  microsoft:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft.mrs'
  microsoft_cn:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft@cn.mrs'
  telegram:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.mrs'
  telegram_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/echs-top/proxy@main/rules/mrs/telegram_ip.mrs'
  pixiv:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/pixiv.mrs'
  steam:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/steam.mrs'
  steam_cn:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/steam@cn.mrs'
  twitter:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/twitter.mrs'
  twitter_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/twitter.mrs'
  private:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs'
  private_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs'
  gfw:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/gfw.mrs'
  cn:
    <<: *rp_domain
    format: mrs
    url: 'https://static-file-global.353355.xyz/rules/cn-additional-list.mrs'
  cn_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs'
  spotify:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/spotify.mrs'
  tiktok:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/tiktok.mrs'
  netflix:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/netflix.mrs'
  netflix_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/netflix.mrs'
  cloudflare:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cloudflare.mrs'
  cloudflare_cn:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cloudflare@cn.mrs'
  cloudflare_ip:
    <<: *rp_ip
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cloudflare.mrs'
  apple:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple.mrs'
  connectivity_check:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/connectivity-check.mrs'
  category_ntp:
    <<: *rp_domain
    format: mrs
    url: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ntp.mrs'

# --- 策略组 (Proxy Groups) ---

# 策略组通用配置
group_common_select:
  &group_common_select {
    type: select,
    interval: 600,
    timeout: 3000,
    url: 'https://g.cn/generate_204',
    lazy: false,
    max-failed-times: 3,
  }

group_common_auto:
  &group_common_auto {
    interval: 600,
    timeout: 3000,
    type: url-test,
    tolerance: 100,
    include-all: true,
    url: 'https://g.cn/generate_204',
    lazy: false,
    max-failed-times: 3,
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png',
    hidden: true,
  }

# 通用代理节点组
prox_common:
  &proxies {
    proxies: ['默认节点', '香港', '日本', '美国', '新加坡', '其他'],
  }

proxy-groups:
  - name: '默认节点'
    <<: *group_common_select
    proxies: ['香港', '新加坡', '日本', '美国', '其他']
    icon: 'https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/Macat.png'

  # 地区分组
  - name: '香港'
    <<: *group_common_select
    include-all: true
    proxies: ['香港-自动选择']
    filter: '(?=.*(港|🇭🇰|HK|[Hh]ong\s*[Kk]ong))'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png'
  - name: '香港-自动选择'
    <<: *group_common_auto
    filter: '(?=.*(港|🇭🇰|HK|[Hh]ong\s*[Kk]ong))'

  - name: '新加坡'
    <<: *group_common_select
    include-all: true
    proxies: ['新加坡-自动选择']
    filter: '(?=.*(新加坡|狮城|🇸🇬|SG|[Ss]ingapore))'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png'
  - name: '新加坡-自动选择'
    <<: *group_common_auto
    filter: '(?=.*(新加坡|狮城|🇸🇬|SG|[Ss]ingapore))'

  - name: '日本'
    <<: *group_common_select
    include-all: true
    proxies: ['日本-自动选择']
    filter: '(?=.*(日本|🇯🇵|JP|[Jj]apan))'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png'
  - name: '日本-自动选择'
    <<: *group_common_auto
    filter: '(?=.*(日本|🇯🇵|JP|[Jj]apan))'

  - name: '美国'
    <<: *group_common_select
    include-all: true
    proxies: ['美国-自动选择']
    filter: '(?=.*(美|🇺🇸|US|[Aa]merica|[Uu]nited\s*[Ss]tates))'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png'
  - name: '美国-自动选择'
    <<: *group_common_auto
    filter: '(?=.*(美|🇺🇸|US|[Aa]merica|[Uu]nited\s*[Ss]tates))'

  - name: '其他'
    <<: *group_common_select
    include-all: true
    exclude-filter: '(?i)港|HK|🇭🇰|日本|JP|🇯🇵|美|US|🇺🇸|新加坡|SG|🇸🇬|直连'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/World_Map.png'

  # 分流策略组
  - name: '国外AI'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/ChatGPT.png'

  - name: 'TikTok'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png'

  - name: 'YouTube'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png'

  - name: 'Google'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png'

  - name: 'Telegram'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png'

  - name: 'GitHub'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png'

  - name: 'Microsoft'
    <<: *group_common_select
    proxies: ['默认节点', '直连', '香港', '日本', '美国', '新加坡', '其他']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png'

  - name: 'Apple'
    <<: *group_common_select
    proxies: ['默认节点', '直连', '香港', '日本', '美国', '新加坡', '其他']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png'
    
  - name: 'Cloudflare'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png'

  - name: 'Pixiv'
    <<: [*group_common_select, *proxies]
    icon: 'https://play-lh.googleusercontent.com/Ls9opXo6-wfEWmbBU8heJaFS8HwWydssWE1J3vexIGvkF-UJDqcW7ZMD8w6dQABfygONd4z3Yt4TfRDZAPYq=w480-h960-rw'

  - name: 'Steam'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png'

  - name: 'Twitter'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png'

  - name: 'Spotify'
    <<: *group_common_select
    proxies: ['默认节点', '直连', '香港', '日本', '美国', '新加坡', '其他']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png'

  - name: 'Netflix'
    <<: [*group_common_select, *proxies]
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png'

  - name: 'FCM'
    <<: *group_common_select
    proxies: ['直连', '默认节点', '香港', '日本', '美国', '新加坡', '其他']
    icon: 'https://fastly.jsdelivr.net/gh/MiToverG422/Qure@master/IconSet/Color/fcm.png'

  - name: '广告拦截'
    <<: *group_common_select
    proxies: ['REJECT', 'REJECT-DROP', 'PASS']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Advertising.png'

  - name: '下载专用'
    <<: *group_common_select
    proxies: ['直连', '默认节点']
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Download.png'

  - name: '直连'
    <<: *group_common_select
    proxies: ['🇨🇳 直连（IPv4优先）', '🇨🇳 直连（IPv6优先）', '🇨🇳 直连（双栈）']
    url: 'https://connectivitycheck.platform.hicloud.com/generate_204'
    icon: 'https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/China_Map.png'

# --- 路由规则 (Rules) ---
rules:
  # 私有网络直连
  - RULE-SET,private,直连
  - RULE-SET,private_ip,直连,no-resolve
  - RULE-SET,embylist_domain,直连

  # 国内直连
  - RULE-SET,steam_cn,直连
  - RULE-SET,epicgames,直连
  - RULE-SET,nvidia_cn,直连
  - RULE-SET,microsoft_cn,直连
  - RULE-SET,cloudflare_cn,直连

  # 进程规则
  - RULE-SET,DownloadApps,下载专用 # 常见磁力下载软件
  - PROCESS-NAME,com.perol.pixez,Pixiv
  - PROCESS-NAME,com.perol.play.pixez,Pixiv

  # 广告拦截
  - RULE-SET,adblockmihomolite,广告拦截

  # 阻断 YouTube UDP 流量
  - AND,((NETWORK,UDP),(DST-PORT,443),(RULE-SET,youtube)),REJECT

  # 代理规则（域名）
  - RULE-SET,ai,国外AI
  - RULE-SET,youtube,YouTube
  - RULE-SET,googlefcm,FCM
  - RULE-SET,google,Google
  - RULE-SET,github,GitHub
  - RULE-SET,microsoft,Microsoft
  - RULE-SET,apple,Apple
  - RULE-SET,telegram,Telegram
  - RULE-SET,cloudflare,Cloudflare
  - RULE-SET,pixiv,Pixiv
  - RULE-SET,steam,Steam
  - RULE-SET,twitter,Twitter
  - RULE-SET,spotify,Spotify
  - RULE-SET,tiktok,TikTok
  - RULE-SET,netflix,Netflix

  # 代理规则（IP）
  - RULE-SET,google_ip,Google,no-resolve
  - RULE-SET,telegram_ip,Telegram,no-resolve
  - RULE-SET,twitter_ip,Twitter,no-resolve
  - RULE-SET,cloudflare_ip,Cloudflare,no-resolve
  - RULE-SET,netflix_ip,Netflix,no-resolve

  # 兜底规则
  - RULE-SET,gfw,默认节点
  - RULE-SET,cn,直连
  - DOMAIN-WILDCARD,*.cn,直连
  - RULE-SET,cn_ip,直连
  - MATCH,默认节点
